import { parkinsans } from "@/lib/fonts";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full ${parkinsans.className}`}>
      <body className="h-full bg-purple-200">
        <HeroUIProvider>{children}</HeroUIProvider>
      </body>
    </html>
  );
}
